version: '3'

services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    restart: always
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    environment:
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: secret